#pragma once

#include "lexer.h"
#include "parser.h"
#include "symtab.h"
#include "encoder.h"

#include <iostream>

namespace lc3kit::lasm {
    /**
     * @brief Maps source line numbers to assembled memory addresses.
     */
    using lines_addrs_t = std::unordered_map<uint, std_word_t>;

    /**
     * @brief High-level assembler pipeline for tokenization, parsing, symbol resolution,
     * and instruction encoding.
     */
    class Asm {
        protected:
            Lexer             m_lexer   {};
            Parser            m_parser  {};
            SymTableGenerator m_symgen  {};
            Encoder           m_encoder {};
            errors_t          m_errors  {};
            bool              m_ext   = false;

            /**
             * @brief Collect stage diagnostics into the assembler error list.
             *
             * @param errs Error list produced by one pipeline stage.
             *
             * @return `true` when the stage produced no errors, otherwise `false`.
             */
            bool collect(const errors_t& errs) {
                if (errs.empty()) {
                    return true;
                }

                m_errors.insert(m_errors.end(), errs.begin(), errs.end());
                
                return false;
            }

        public:
            /**
             * @brief Enable or disable the lc3kit extension instruction set.
             *
             * @param enabled `true` to enable extension opcodes, `false` otherwise.
             */
            void set_ext_enabled(bool enabled) { 
                m_ext = enabled;
                m_lexer.set_ext_enabled(enabled);
                m_parser.set_ext_enabled(enabled);
                m_encoder.set_ext_enabled(enabled);
            }

            /**
             * @brief Check whether extension instructions are enabled.
             *
             * @return `true` when the extension instruction set is active.
             */
            bool is_ext_enabled() const { 
                return m_ext;    
            }

            /**
             * @brief Check whether the assembler is in a clean state.
             *
             * @return `true` when no diagnostics have been recorded.
             */
            bool ok() const { return m_errors.empty(); }

            /**
             * @brief Get the accumulated assembler diagnostics.
             *
             * @return Read-only list of all errors collected during the pipeline.
             */
            const errors_t& errors() const { return m_errors; }

            /**
             * @brief Get the symbol table generated by the assembler.
             *
             * @return Current symbol table mapping labels to addresses.
             */
            const sym_table_t& sym_table() const { return m_symgen.get(); }

            /**
             * @brief Get the successfully encoded program sections.
             *
             * @return Encoded assembly sections produced by the encoder.
             */
            const sections_t& sections() const { return m_encoder.sections(); }

            /**
             * @brief Map each source line to the memory address it assembles to.
             *
             * @return A map from one-based source line numbers to assembled addresses.
             */
            lines_addrs_t line_addresses() const {
                lines_addrs_t result;
                
                for (const auto& ins : m_parser.get_instructions()) {
                    if (ins->pos.line > 0 && ins->address > 0) {
                        result[(uint)ins->pos.line] = ins->address;
                    }
                }
                return result;
            }
            
            // -- pipeline

            /**
             * @brief Assemble source code from an in-memory source buffer.
             *
             * Runs the lexer, parser, symbol generation, and encoding passes in order.
             *
             * @param src Source text and metadata to assemble.
             *
             * @return `true` when the full pipeline succeeded, `false` otherwise.
             */
            bool assemble(source_code src) {
                m_errors  = {};
                
                // stage 1 - lex
                m_lexer.tokenize(src);

                if (!collect(m_lexer.errors())) {
                    return false;
                }

                // stage 2 - parse
                m_parser.parse(m_lexer.tokens());

                if (!collect(m_parser.errors())) {
                    return false;
                }

                
                // stage 3 - pass 1: build symbol table
                m_symgen.generate(m_parser.get_instructions());
                
                if (!collect(m_symgen.errors())) {
                    return false;
                }

                // stage 4 - pass 2: encode
                m_encoder.encode(m_parser.get_instructions(), m_symgen.get());

                if (!collect(m_encoder.errors())) {
                    return false;
                }

                return true;
            }

            /**
             * @brief Assemble source code read from an input stream.
             *
             * @param stream Input stream containing assembly source.
             *
             * @return `true` when assembly succeeds, `false` when any stage reports an
             * error.
             */
            bool assemble(std::istream& stream) {
                std::string content((std::istreambuf_iterator<char>(stream)), std::istreambuf_iterator<char>());

                return assemble({ content.c_str(), (uint32_t)content.size() });
            }
                
            // -- output

            /**
             * @brief Dump assembled sections as a big-endian binary stream.
             *
             * @param out Output stream receiving the encoded binary image.
             */
            void dump(std::ostream& out) const {
                for (const auto& section : m_encoder.sections()) {
                    uint16_t origin = section.origin;
                    out.put((char)(origin >> 8));
                    out.put((char)(origin & 0xFF));

                    for (std_word_t word : section.words) {
                        out.put((char)(word >> 8));
                        out.put((char)(word & 0xFF));
                    }
                }
            }

        };

} // namespace lc3kit::lasm